export interface SolutionPage {
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  features: string[];
  benefits: string[];
  integrations: string[];
  hero_image?: string;
  icon: string;
  color_theme: string;
  meta_title?: string;
  meta_description?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  stats_json?: { label: string; value: string }[];
  cta_title?: string;
  cta_description?: string;
  cta_button_label?: string;
  features_title?: string;
  benefits_title?: string;
  faq_json?: { question: string; answer: string }[];
  steps_json?: { title: string; description: string }[];
  steps_title?: string;
  video_url?: string;
  video_title?: string;
  screenshots_json?: string[];
  screenshots_title?: string;
  differentials_json?: { icon: string; title: string; description: string }[];
  differentials_title?: string;
  highlight_title?: string;
  highlight_text?: string;
  testimonial_quote?: string;
  testimonial_author?: string;
  testimonial_role?: string;
  secondary_cta_label?: string;
  secondary_cta_link?: string;
  page_template?: string;
}
